Feature/style emotionform
Jennifer-Hinrichsen/emotion-tracker pull request #27
Opened 2024-10-16 11:13 UTC by Leon910

2024-10-17 11:02 UTC, laurasliwa requested changes
Very nice styling!

I commented a few minor things. But have two things I want to shine light on:

1. Your User Stories states that the width of the form should be fixed. Which means it stays the same width or only gets smaller when I change the size of the window.

2. Even though I like the color palette a lot I would suggest that you check your colors for contrast for readability. For example [here](https://webaim.org/resources/contrastchecker/) or google contrast checker.

Apart from that keep up with the good work :)

2024-10-17 11:02 UTC, laurasliwa commented on components/EmotionForm.js
> +  // const hasError = formError !== "";
You can delete commented out code.

2024-10-17 11:02 UTC, laurasliwa commented on components/EmotionForm.js
> +  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
Stick with either hex code or rgba in your code.

2024-10-17 11:02 UTC, laurasliwa commented on components/EmotionForm.js
> +  color: white;
Use either hex code or rgba.

2024-10-17 11:02 UTC, laurasliwa commented on pages/index.js
> +  padding: 0 0 20px 0;
Just a suggestion (I forget this also all the time): You can write `padding-bottom: 20px;` instead of all the zeros. But that's just a personal taste.

2024-10-18 06:58 UTC, Leon910 commented
Thanks a lot for your great review @laurasliwa.

We adapted your good point regarding the acceptance criteria and will discuss the colorset as well. We as well corrected the minor styling issues you found!

2024-10-18 07:52 UTC, F-Kirchhoff approved these changes
Hey Moodwave,
great job with solving the merge conflict. I only found very basic issues, so they are fast to fix. You can go to QA after applying the suggestions.

2024-10-18 07:52 UTC, F-Kirchhoff commented on components/EmotionForm.js
> +                <option key={index} value={emotion}>
here is a very typical mistake: you are using the index as a key. Please remember this: Never use the index of an array as the key. Please use emotion instead or give your emotions ids.

2024-10-18 07:52 UTC, F-Kirchhoff commented on components/EmotionForm.js
> +          ></StyledTextArea>
please use self closing tags whenever possible.

2024-10-18 07:52 UTC, F-Kirchhoff commented on components/EmotionForm.js
>      <>
these fragments are unnecessary (only one child)

2024-10-21 08:40 UTC, merged