Feature/filter slider
Jennifer-Hinrichsen/emotion-tracker pull request #58
Opened 2024-11-11 11:03 UTC by StephieTack

2024-11-11 11:40 UTC, F-Kirchhoff requested changes
Hey,
this is great code and a rather tricky feature to implement. I only have one big concern with the PR: your component EmotionList displays way more than the name suggests. Please split your code into a Filter and List component and render both from the page component in index.js.

2024-11-11 11:40 UTC, F-Kirchhoff commented on components/EmotionList.js
> +  }
instead onf handleScroll you can pass updateArrowVisibility to the eventHandler prop.

2024-11-11 11:40 UTC, F-Kirchhoff commented on components/EmotionList.js
> +            <StyledClearFilter onClick={() => setSelectedFilter("")}>
Please rename this that it includes "button" in the name.

2024-11-11 11:40 UTC, F-Kirchhoff commented on components/EmotionList.js
>  import styled from "styled-components";
You have now a lot of code in your EmotionList Component. Please split this up such that the filter display is its own component and is called by your page index.js next to the Emotionlist.

2024-11-11 11:40 UTC, F-Kirchhoff commented on components/EmotionList.js
> +    `
you can use the function `css` from styled-components here, that helps to write this nested css code.
```suggestion
    css`
```

2024-11-11 12:26 UTC, StephieTack commented on components/EmotionList.js
> +            <StyledClearFilter onClick={() => setSelectedFilter("")}>
I did. I was not sure because at least this are no buttons. It is existing in the li-tags.

2024-11-12 08:08 UTC, ahohnsen approved these changes
Very nice feature. ✌🏼

2024-11-12 13:23 UTC, F-Kirchhoff approved these changes
Fantastic, I think this is what a library would have done instead, but recreating it is great as well.

2024-11-12 13:23 UTC, F-Kirchhoff commented on components/EmotionListAndFilter/useScreenSize.js
> +    if (typeof window !== "undefined") {
a useEffect is only run in the client, therefore you don't need to check if window does exist.

2024-11-12 13:23 UTC, F-Kirchhoff commented on components/EmotionListAndFilter/useScreenSize.js
> +    if (typeof window !== "undefined") {
usually, hooks are placed in a folder `lib/hooks/` not in the components folder.

2024-11-12 13:25 UTC, F-Kirchhoff commented on components/EmotionListAndFilter/Filter.js
> +import styled, { css } from "styled-components";
please move these files out into the components folder and remove this folder.

2024-11-13 09:04 UTC, merged