Feature/image upload
Jennifer-Hinrichsen/emotion-tracker pull request #98
Opened 2024-12-15 19:56 UTC by StephieTack

2024-12-16 10:23 UTC, F-Kirchhoff requested changes
This looks great! There is only one small suggestion that I would like you to implement: please reuse the "PUT" endpoint of your API.

2024-12-16 10:23 UTC, F-Kirchhoff commented on pages/emotion/[id]/index.js
> +      }
since you are not using the entryData that is sent back by the backend when requesting this endpoint, you can also reuse the "PUT" endpoint which does exactly the same, but without sending the updated entry back. (By only sending `{imageURL: "..."}` to the "PUT" endpoint, only the imageUrl field in the entry is changed, everything else is kept unchanged. This is how mongoose implemented the `findByIdAndUpdate` method.

2024-12-16 10:23 UTC, F-Kirchhoff commented on pages/api/emotionEntries/[id].js
> +    }
this "PATCH" endpoint is not needed

2024-12-16 10:23 UTC, F-Kirchhoff commented on components/ImageUpload.js
> +        await onSubmit(data);
This code will work fine, but you are doing a bit of unneeded extra work. Feel free to ignore it but I want to include this hint for completeness: 
This is what happens in your code: 

`client` -- image data  --> `backend: api/upload` -- image url --> `client` -- image url --> `backend: update entry` --> `client`

Do you see how the client is in between the image upload and the update of the entry, but only passing the image url to it without doing anything? You could do this instead: 

`client` -- image data  --> `backend: api/upload` -- image url --> `backend: update entry` --> `client`. 

So the upload endpoint can talk directly to the update entry endpoint without the client as a middle man. I think you can stick with your solution, but be aware of the other options.

2024-12-17 15:08 UTC, Roland-Hufnagel approved these changes
LGTM

2024-12-18 09:31 UTC, merged